In [1]:
import numpy as np

# Example input embeddings
X = np.array([
    [1, 0, 1],
    [0, 2, 0],
    [1, 1, 1]
])

# Weight matrices
Wq = np.random.rand(3, 3)
Wk = np.random.rand(3, 3)
Wv = np.random.rand(3, 3)

# Compute Q, K, V
Q = X @ Wq
K = X @ Wk
V = X @ Wv

# Compute attention scores
scores = Q @ K.T

# Scale scores
d_k = K.shape[1]
scaled_scores = scores / np.sqrt(d_k)

# Softmax function
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

# Attention weights
attention_weights = softmax(scaled_scores)

# Output
output = attention_weights @ V

print("Attention Weights:\n", attention_weights)
print("Output:\n", output)

Attention Weights:
 [[0.10039962 0.37560818 0.5239922 ]
 [0.19320222 0.37897732 0.42782046]
 [0.07139785 0.37410081 0.55450134]]
Output:
 [[0.90492473 0.1760064  1.3878886 ]
 [0.88641701 0.17468168 1.35275365]
 [0.91113905 0.17654221 1.39941579]]
